
export const ActionTypes = {
   PLAY_MUSIC:"PLAY_MUSIC",
   GET_LIST:"GET_LIST",
   ANIMATION_DISK:"ANIMATION_DISK",
   ENABLE_PAGE:" ENABLE_PAGE",
   SELECT_ITEM:"SELECT_ITEM",
   REGISTER:"REGISTER",
   LOGIN:"LOGIN",
   ALBUM:"ALBUM",
   ADD_ALBUM:"ADD_ALBUM",
   UPDATE_ALBUM:"UPDATE_ALBUM",
   DELETE_ALBUM:"DELETE_ALBUM",
   GET_ALL_ALBUM:"GET_ALL_ALBUM",
   SELECT_ALBUM:"SELECT_ALBUM",
   ADD_SONG:"ADD_SONG",
   DELETE_SONG:"DELETE_SONG",
   GET_SONG:"GET_SONG",
   TOP_WEEK:"TOP_WEEK",
   TOP_MONTH:"TOP_MONTH",
   ENABLE_MOBILE_MENU:"ENABLE_MOBILE_MENU"

  }